### ISSUE TITLE
jsdom missing error when trying to run dlint tests

### ISSUE THREAD

**Issue by msridhar** [ksen007/jalangi2analyses#2]
I followed the installation instructions in the README, but when I try to run the dlint tests, I see the following error several times:
```
Error: Cannot find module 'jsdom'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /private/tmp/dymAnalysis/jalangi2analyses/src/js/analyses/dlint/utils/document.js:30:15
    at Object.<anonymous> (/private/tmp/dymAnalysis/jalangi2analyses/src/js/analyses/dlint/utils/document.js:91:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```
Looks like maybe there should be a `package.json` specifying a `jsdom` dependence?

**Comment by JacksonGL** [comment]
I will try to debug it tonight after I get home from work.
Can you try the following command to install jsdom 3.1.2 and let me know if the problem still exists? Thanks.

```
npm install jsdom@3.1.2
```

**Comment by msridhar** [comment]
I then get a similar error since `xmldom` is not installed.

**Comment by JacksonGL** [comment]
Sorry for the trouble you have gone through. Are there more packages missing after installing `xmldom`? I have also updated the repository. Please run a `git pull` before running the dlint tests.
